# Generated by Django 3.2.13 on 2022-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_kam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
    ]
