# Generated by Django 3.2.13 on 2022-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220920_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.TextField(),
        ),
    ]
