# Generated by Django 3.2.13 on 2022-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.CharField(max_length=244444),
        ),
    ]
