# Generated by Django 3.2.13 on 2022-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_home_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=244444)),
                ('quantity', models.CharField(max_length=244444)),
                ('speed', models.CharField(max_length=244444)),
            ],
        ),
    ]
